{
 "title": "Parity metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "classic peer count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "peer_count{chain=\"classic\"} "
    }
   ]
  },
  {
   "title": "classic version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "\nversion{chain=\"classic\"}",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "classic latest hash",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "latest_hash{chain=\"classic\"}"
    }
   ]
  },
  {
   "title": "classic height",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "latest_height{chain=\"classic\"}"
    }
   ]
  }
 ]
}